[stream]
x = 1280
y = 720
fps = 15
# format: jpeg, webp, avif
format = jpeg
quality = 100
compression = 50

[audio]
enable = 1
bitrate = 64000

[server]
port = 2222
ip = 0.0.0.0

[videoin]
autosuspend = 1
USBUVCid = 1-1
VideoDeviceIn = /dev/video0
devicenotreadyimage = WeFight_WeWin-UHD-DPST.png

[KVM]
# config for KVM IO and USB HID controller
controlSerialPort = /dev/ttyACM0
baudrate = 115200
maxCommandQueueSize = 10
commandRateLimit = 100
